feat: Criação da página sobre
ufrb-engenhe-jr/ufrb-engenhe-jr.github.io pull request #11
Opened 2022-09-14 23:09 UTC by VictorFranke

Criei a página sobre utilizando parte do estilo utilizado por Gabriel.

2022-09-14 23:11 UTC, jeovanedossantossantos requested changes
Teste

2022-09-14 23:14 UTC, jeovanedossantossantos requested changes
sdfsd

2022-09-14 23:17 UTC, jeovanedossantossantos commented on sobre.html
> +                inconformados com a falta de desafios profissionais arregaçaram as mangas e resolveram fundar aquela que seria uma das empresas Juniores que mais
Trocar texto

2022-09-14 23:18 UTC, jeovanedossantossantos requested changes
243243adsad

2022-09-23 00:20 UTC, jeovanedossantossantos approved these changes

2022-09-23 00:26 UTC, jeovanedossantossantos approved these changes

2022-09-23 00:30 UTC, Gabriel-MarcoSilva approved these changes

2022-09-23 00:38 UTC, merged