03 criar section
ufrb-engenhe-jr/ufrb-engenhe-jr.github.io pull request #9
Opened 2022-09-10 02:19 UTC by Gabriel-MarcoSilva

Finalização da task, adicionando a section contendo a logo e informações da Engenhe, com estilização e animação

2022-09-10 14:35 UTC, jeovanedossantossantos commented on style.css
> +    display: grid;
Parabéns Gabriel, gostei do que você fez, visualmente muito interessante.
  
Observei que não esta responsivo.

![image](https://user-images.githubusercontent.com/60934938/189488082-10520943-ab1b-4f6a-8ac5-35d7599c8fd4.png)

Seria interessante se quando ele diminuísse de tamanho o texto fosse para baixo, com na imagem abaixo.

![image](https://user-images.githubusercontent.com/60934938/189488152-0754fbe1-0217-4b2b-a887-21efdcf60204.png)

2022-09-10 14:42 UTC, jeovanedossantossantos requested changes
Muito bem Gabriel, estou solicitando o code review para irmos nos acostumando com essas ferramentas, e fiz uma observação para você rever uma parte do que você fez.

Observei que tem conflito, siga os seguites passos.

Na sua bracht, digite no termina git pull origin main, isso vai  pegar o que está na bracht main assim o conflito ira aparecer.
Com é simples apenas deixe o que você fez, provavelmente  deve é a palavra "teste" que eu coloque no index do main. então é só você tira e commitar novamente.

2022-09-23 00:17 UTC, jeovanedossantossantos approved these changes

2022-09-23 00:17 UTC, jeovanedossantossantos approved these changes

2022-09-23 00:19 UTC, jeovanedossantossantos approved these changes

2022-09-23 00:25 UTC, jeovanedossantossantos approved these changes

2022-09-23 00:29 UTC, VictorFranke approved these changes

2022-09-23 00:31 UTC, ufrb-engenhe-jr approved these changes

2022-09-23 00:31 UTC, merged